### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mrasljic**
want to download the files

### CODE REVIEW

**Comment by thenitai** [comment]
What is this? A pull request or a question?

**Comment by mrasljic** [comment]
Sorry. Wanted to get the files, but there was no download button. Later saw
that there is one in the previous directory.
But, as long as we are here- how do I setup your theme? I also have a theme
"r <https://readthedocs.org/>eadthedocs" installed. I tried to put the
"theme_dir:
readthedocshm" in the mkdocs.yml file and grabed the folder readthedocshm from
your url and placed it in my mkdocs folder. But it is still not making any
changes. The command line says "ERROR   -  Config value: 'theme_dir'.
Error: The path readthedocshm doesn't exist ". I tried to put the folder
"readthedocshm" in folder "mkdocs" and later also without that "nkdocs"
folder.
Btw, I am trying to get the functionality that you have for
the COLLAPSIBLE NAVIGATION.

Do you have any suggestions or idea on why am I getting that error when I
put everything where it is suppose to be?
Thank you for your time.

Regards,
Milan

**Comment by mrasljic** [comment]
Found the problem. I put the directory in DOCS directory instead of beside
that directory. Now it works fine. Nice job. There are some problems with
cookies and when refreshing a page that does not have the collapsed menu
but in url the specific page is specified. But ok.
Also I can see that only FROM the 3rd branch in the tree there is an option
for collapsing the menu. Is it easy to make the 2nd branch collapsible
also? I haven't tried yet and I wanted to ask you first.

**Comment by mrasljic** [comment]
Hello again. I managed to change it so that the collapsing could be done
from the beginning of the branching. Sending you the file in the attachment.

On Thu, Nov 24, 2016 at 10:10 AM, Milan Rašljić <m.rasljic@thepimcompany.com
> wrote:

> Found the problem. I put the directory in DOCS directory instead of beside
> that directory. Now it works fine. Nice job. There are some problems with
> cookies and when refreshing a page that does not have the collapsed menu
> but in url the specific page is specified. But ok.
> Also I can see that only FROM the 3rd branch in the tree there is an
> option for collapsing the menu. Is it easy to make the 2nd branch
> collapsible also? I haven't tried yet and I wanted to ask you first.
>
> On Thu, Nov 24, 2016 at 8:50 AM, Milan Rašljić <

**Comment by thenitai** [comment]
Ok. Can you please take our branch again and update your code and then do a proper pull request again? This looks rather messy here right now :)

Thank you.

**Comment by mrasljic** [comment]
Sorry about that. Just got back to work. It's Monday.

**Pull request closed without merging**
